### ISSUE TITLE
Archived / Deprecated

### ISSUE THREAD

**Issue by Mike-EEE** [DragonSpark/Framework#2]
This project is being archived.  You can see my latest efforts which are based on this project here:
https://github.com/SuperDotNet/Super.NET

I should have done this sooner but am making an effort now since I mentioned this in a blog post here:
https://blog.superdotnet.run/2019/05/super.net-v0.0.1/

See you there @ Super.NET. :) 🎉

**Comment by Mike-EEE** [comment]
LOLOLOLOL... FOOLED YOU. 😁

https://youtu.be/tSnp6iC_QUc

HEHEHEHEHE

![](https://i.imgur.com/6siqjaz.png)

Yeah, I decided to UNARCHIVE this project, and continue it.  Details here:

https://blog.dragonspark.us/2019/11/november-2019-status-update/

✌

**Comment by JasonLConway** [comment]
HA!  Well, when you know - you know.  :)

Looking forward to learning more!

Jason
